### ISSUE TITLE
Endless exceptions with or without players

### ISSUE THREAD

**Issue by AWL-Gaming** [HnZGaming/TorchMonitor#2]
The console is flooded with the following error:
```
[ERROR]  IntervalRunner: System.ArgumentException: null or empty: value
   at Utils.General.DebugUtils.ThrowIfNullOrEmpty(String self, String msg)
   at InfluxDb.Client.Write.InfluxDbPoint.Tag(String key, String value)
   at TorchMonitor.Monitors.OnlinePlayersMonitor.OnInterval(Int32 intervalsSinceStart)
   at Intervals.IntervalRunner.<>c__DisplayClass7_0.<RunIntervalOnce>b__0(IIntervalListener listener)
System.ArgumentException: null or empty: value
   at Utils.General.DebugUtils.ThrowIfNullOrEmpty(String self, String msg)
   at InfluxDb.Client.Write.InfluxDbPoint.Tag(String key, String value)
   at TorchMonitor.Monitors.OnlinePlayersMonitor.OnInterval(Int32 intervalsSinceStart)
   at Intervals.IntervalRunner.<>c__DisplayClass7_0.<RunIntervalOnce>b__0(IIntervalListener listener)
```
While the plugin and DB work flawlessly, this makes the log files really large on a populated server, as well as hard to read.

![image](https://user-images.githubusercontent.com/22678541/166910059-33eeae21-6dab-45c0-be86-dc18b914694f.png)

**Comment by ryo0ka** [comment]
closed as resolved on discord
